// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentPB.proto

package datawave.annotation.protobuf;

/**
 * <pre>
 * boundaries of this segment, depending on the segment type, it might be a boundary defined by time or position.
 * </pre>
 *
 * Protobuf type {@code datawave.annotation.protobuf.SegmentBoundary}
 */
public final class SegmentBoundary extends com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.SegmentBoundary)
                SegmentBoundaryOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use SegmentBoundary.newBuilder() to construct.
    private SegmentBoundary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private SegmentBoundary() {
        type_ = 0;
        start_ = "";
        end_ = "";
        rotation_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    private SegmentBoundary(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        int rawValue = input.readEnum();
                        datawave.annotation.protobuf.SegmentBoundaryType value = datawave.annotation.protobuf.SegmentBoundaryType.valueOf(rawValue);
                        if (value == null) {
                            unknownFields.mergeVarintField(1, rawValue);
                        } else {
                            bitField0_ |= 0x00000001;
                            type_ = rawValue;
                        }
                        break;
                    }
                    case 18: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000002;
                        start_ = bs;
                        break;
                    }
                    case 26: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000004;
                        end_ = bs;
                        break;
                    }
                    case 32: {
                        bitField0_ |= 0x00000008;
                        rotation_ = input.readUInt32();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentBoundary_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentBoundary_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.SegmentBoundary.class,
                                        datawave.annotation.protobuf.SegmentBoundary.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;

    /**
     * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
     */
    public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
     */
    public datawave.annotation.protobuf.SegmentBoundaryType getType() {
        datawave.annotation.protobuf.SegmentBoundaryType result = datawave.annotation.protobuf.SegmentBoundaryType.valueOf(type_);
        return result == null ? datawave.annotation.protobuf.SegmentBoundaryType.TIME : result;
    }

    public static final int START_FIELD_NUMBER = 2;
    private volatile java.lang.Object start_;

    /**
     * <code>required string start = 2;</code>
     */
    public boolean hasStart() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required string start = 2;</code>
     */
    public java.lang.String getStart() {
        java.lang.Object ref = start_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                start_ = s;
            }
            return s;
        }
    }

    /**
     * <code>required string start = 2;</code>
     */
    public com.google.protobuf.ByteString getStartBytes() {
        java.lang.Object ref = start_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            start_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int END_FIELD_NUMBER = 3;
    private volatile java.lang.Object end_;

    /**
     * <code>required string end = 3;</code>
     */
    public boolean hasEnd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>required string end = 3;</code>
     */
    public java.lang.String getEnd() {
        java.lang.Object ref = end_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                end_ = s;
            }
            return s;
        }
    }

    /**
     * <code>required string end = 3;</code>
     */
    public com.google.protobuf.ByteString getEndBytes() {
        java.lang.Object ref = end_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            end_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ROTATION_FIELD_NUMBER = 4;
    private int rotation_;

    /**
     * <code>optional uint32 rotation = 4;</code>
     */
    public boolean hasRotation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
    }

    /**
     * <code>optional uint32 rotation = 4;</code>
     */
    public int getRotation() {
        return rotation_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        if (!hasType()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasStart()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasEnd()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeEnum(1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, start_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, end_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
            output.writeUInt32(4, rotation_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, start_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, end_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
            size += com.google.protobuf.CodedOutputStream.computeUInt32Size(4, rotation_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof datawave.annotation.protobuf.SegmentBoundary)) {
            return super.equals(obj);
        }
        datawave.annotation.protobuf.SegmentBoundary other = (datawave.annotation.protobuf.SegmentBoundary) obj;

        boolean result = true;
        result = result && (hasType() == other.hasType());
        if (hasType()) {
            result = result && type_ == other.type_;
        }
        result = result && (hasStart() == other.hasStart());
        if (hasStart()) {
            result = result && getStart().equals(other.getStart());
        }
        result = result && (hasEnd() == other.hasEnd());
        if (hasEnd()) {
            result = result && getEnd().equals(other.getEnd());
        }
        result = result && (hasRotation() == other.hasRotation());
        if (hasRotation()) {
            result = result && (getRotation() == other.getRotation());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasType()) {
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
        }
        if (hasStart()) {
            hash = (37 * hash) + START_FIELD_NUMBER;
            hash = (53 * hash) + getStart().hashCode();
        }
        if (hasEnd()) {
            hash = (37 * hash) + END_FIELD_NUMBER;
            hash = (53 * hash) + getEnd().hashCode();
        }
        if (hasRotation()) {
            hash = (37 * hash) + ROTATION_FIELD_NUMBER;
            hash = (53 * hash) + getRotation();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseDelimitedFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.SegmentBoundary parseFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(datawave.annotation.protobuf.SegmentBoundary prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * boundaries of this segment, depending on the segment type, it might be a boundary defined by time or position.
     * </pre>
     *
     * Protobuf type {@code datawave.annotation.protobuf.SegmentBoundary}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.SegmentBoundary)
                    datawave.annotation.protobuf.SegmentBoundaryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentBoundary_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentBoundary_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.SegmentBoundary.class,
                                            datawave.annotation.protobuf.SegmentBoundary.Builder.class);
        }

        // Construct using datawave.annotation.protobuf.SegmentBoundary.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
        }

        public Builder clear() {
            super.clear();
            type_ = 0;
            bitField0_ = (bitField0_ & ~0x00000001);
            start_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            end_ = "";
            bitField0_ = (bitField0_ & ~0x00000004);
            rotation_ = 0;
            bitField0_ = (bitField0_ & ~0x00000008);
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentBoundary_descriptor;
        }

        public datawave.annotation.protobuf.SegmentBoundary getDefaultInstanceForType() {
            return datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance();
        }

        public datawave.annotation.protobuf.SegmentBoundary build() {
            datawave.annotation.protobuf.SegmentBoundary result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public datawave.annotation.protobuf.SegmentBoundary buildPartial() {
            datawave.annotation.protobuf.SegmentBoundary result = new datawave.annotation.protobuf.SegmentBoundary(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.type_ = type_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.start_ = start_;
            if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                to_bitField0_ |= 0x00000004;
            }
            result.end_ = end_;
            if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                to_bitField0_ |= 0x00000008;
            }
            result.rotation_ = rotation_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof datawave.annotation.protobuf.SegmentBoundary) {
                return mergeFrom((datawave.annotation.protobuf.SegmentBoundary) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(datawave.annotation.protobuf.SegmentBoundary other) {
            if (other == datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance())
                return this;
            if (other.hasType()) {
                setType(other.getType());
            }
            if (other.hasStart()) {
                bitField0_ |= 0x00000002;
                start_ = other.start_;
                onChanged();
            }
            if (other.hasEnd()) {
                bitField0_ |= 0x00000004;
                end_ = other.end_;
                onChanged();
            }
            if (other.hasRotation()) {
                setRotation(other.getRotation());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            if (!hasType()) {
                return false;
            }
            if (!hasStart()) {
                return false;
            }
            if (!hasEnd()) {
                return false;
            }
            return true;
        }

        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            datawave.annotation.protobuf.SegmentBoundary parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (datawave.annotation.protobuf.SegmentBoundary) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private int type_ = 0;

        /**
         * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
         */
        public datawave.annotation.protobuf.SegmentBoundaryType getType() {
            datawave.annotation.protobuf.SegmentBoundaryType result = datawave.annotation.protobuf.SegmentBoundaryType.valueOf(type_);
            return result == null ? datawave.annotation.protobuf.SegmentBoundaryType.TIME : result;
        }

        /**
         * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
         */
        public Builder setType(datawave.annotation.protobuf.SegmentBoundaryType value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            type_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
         */
        public Builder clearType() {
            bitField0_ = (bitField0_ & ~0x00000001);
            type_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object start_ = "";

        /**
         * <code>required string start = 2;</code>
         */
        public boolean hasStart() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string start = 2;</code>
         */
        public java.lang.String getStart() {
            java.lang.Object ref = start_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    start_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>required string start = 2;</code>
         */
        public com.google.protobuf.ByteString getStartBytes() {
            java.lang.Object ref = start_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                start_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required string start = 2;</code>
         */
        public Builder setStart(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            start_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>required string start = 2;</code>
         */
        public Builder clearStart() {
            bitField0_ = (bitField0_ & ~0x00000002);
            start_ = getDefaultInstance().getStart();
            onChanged();
            return this;
        }

        /**
         * <code>required string start = 2;</code>
         */
        public Builder setStartBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            start_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object end_ = "";

        /**
         * <code>required string end = 3;</code>
         */
        public boolean hasEnd() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string end = 3;</code>
         */
        public java.lang.String getEnd() {
            java.lang.Object ref = end_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    end_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>required string end = 3;</code>
         */
        public com.google.protobuf.ByteString getEndBytes() {
            java.lang.Object ref = end_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                end_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required string end = 3;</code>
         */
        public Builder setEnd(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000004;
            end_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>required string end = 3;</code>
         */
        public Builder clearEnd() {
            bitField0_ = (bitField0_ & ~0x00000004);
            end_ = getDefaultInstance().getEnd();
            onChanged();
            return this;
        }

        /**
         * <code>required string end = 3;</code>
         */
        public Builder setEndBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000004;
            end_ = value;
            onChanged();
            return this;
        }

        private int rotation_;

        /**
         * <code>optional uint32 rotation = 4;</code>
         */
        public boolean hasRotation() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional uint32 rotation = 4;</code>
         */
        public int getRotation() {
            return rotation_;
        }

        /**
         * <code>optional uint32 rotation = 4;</code>
         */
        public Builder setRotation(int value) {
            bitField0_ |= 0x00000008;
            rotation_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional uint32 rotation = 4;</code>
         */
        public Builder clearRotation() {
            bitField0_ = (bitField0_ & ~0x00000008);
            rotation_ = 0;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.SegmentBoundary)
    }

    // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.SegmentBoundary)
    private static final datawave.annotation.protobuf.SegmentBoundary DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new datawave.annotation.protobuf.SegmentBoundary();
    }

    public static datawave.annotation.protobuf.SegmentBoundary getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<SegmentBoundary> PARSER = new com.google.protobuf.AbstractParser<SegmentBoundary>() {
        public SegmentBoundary parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return new SegmentBoundary(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<SegmentBoundary> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SegmentBoundary> getParserForType() {
        return PARSER;
    }

    public datawave.annotation.protobuf.SegmentBoundary getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
