// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentPB.proto

package datawave.annotation.protobuf;

/**
 * Protobuf enum {@code datawave.annotation.protobuf.SegmentBoundaryType}
 */
public enum SegmentBoundaryType implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TIME = 0;</code>
     */
    TIME(0),
    /**
     * <code>POSITION = 1;</code>
     */
    POSITION(1),;

    /**
     * <code>TIME = 0;</code>
     */
    public static final int TIME_VALUE = 0;
    /**
     * <code>POSITION = 1;</code>
     */
    public static final int POSITION_VALUE = 1;

    public final int getNumber() {
        return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SegmentBoundaryType valueOf(int value) {
        return forNumber(value);
    }

    public static SegmentBoundaryType forNumber(int value) {
        switch (value) {
            case 0:
                return TIME;
            case 1:
                return POSITION;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SegmentBoundaryType> internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<SegmentBoundaryType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<SegmentBoundaryType>() {
        public SegmentBoundaryType findValueByNumber(int number) {
            return SegmentBoundaryType.forNumber(number);
        }
    };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return datawave.annotation.protobuf.SegmentPB.getDescriptor().getEnumTypes().get(0);
    }

    private static final SegmentBoundaryType[] VALUES = values();

    public static SegmentBoundaryType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private SegmentBoundaryType(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:datawave.annotation.protobuf.SegmentBoundaryType)
}
