// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

public interface TextSpanCharsOrBuilder extends
                // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.v1.TextSpanChars)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 start = 1;</code>
     *
     * @return The start.
     */
    int getStart();

    /**
     * <code>int32 end = 2;</code>
     *
     * @return The end.
     */
    int getEnd();
}
