// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

/**
 * Protobuf type {@code datawave.annotation.protobuf.v1.TimeSpanSeconds}
 */
public final class TimeSpanSeconds extends com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.v1.TimeSpanSeconds)
                TimeSpanSecondsOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use TimeSpanSeconds.newBuilder() to construct.
    private TimeSpanSeconds(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private TimeSpanSeconds() {}

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new TimeSpanSeconds();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_TimeSpanSeconds_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_TimeSpanSeconds_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.TimeSpanSeconds.class,
                                        datawave.annotation.protobuf.v1.TimeSpanSeconds.Builder.class);
    }

    public static final int START_FIELD_NUMBER = 1;
    private float start_;

    /**
     * <code>float start = 1;</code>
     *
     * @return The start.
     */
    @java.lang.Override
    public float getStart() {
        return start_;
    }

    public static final int END_FIELD_NUMBER = 2;
    private float end_;

    /**
     * <code>float end = 2;</code>
     *
     * @return The end.
     */
    @java.lang.Override
    public float getEnd() {
        return end_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (start_ != 0F) {
            output.writeFloat(1, start_);
        }
        if (end_ != 0F) {
            output.writeFloat(2, end_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (start_ != 0F) {
            size += com.google.protobuf.CodedOutputStream.computeFloatSize(1, start_);
        }
        if (end_ != 0F) {
            size += com.google.protobuf.CodedOutputStream.computeFloatSize(2, end_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof datawave.annotation.protobuf.v1.TimeSpanSeconds)) {
            return super.equals(obj);
        }
        datawave.annotation.protobuf.v1.TimeSpanSeconds other = (datawave.annotation.protobuf.v1.TimeSpanSeconds) obj;

        if (java.lang.Float.floatToIntBits(getStart()) != java.lang.Float.floatToIntBits(other.getStart()))
            return false;
        if (java.lang.Float.floatToIntBits(getEnd()) != java.lang.Float.floatToIntBits(other.getEnd()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(getStart());
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(getEnd());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseDelimitedFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds parseFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(datawave.annotation.protobuf.v1.TimeSpanSeconds prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code datawave.annotation.protobuf.v1.TimeSpanSeconds}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.v1.TimeSpanSeconds)
                    datawave.annotation.protobuf.v1.TimeSpanSecondsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_TimeSpanSeconds_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_TimeSpanSeconds_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.TimeSpanSeconds.class,
                                            datawave.annotation.protobuf.v1.TimeSpanSeconds.Builder.class);
        }

        // Construct using datawave.annotation.protobuf.v1.TimeSpanSeconds.newBuilder()
        private Builder() {

        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            start_ = 0F;

            end_ = 0F;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_TimeSpanSeconds_descriptor;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.TimeSpanSeconds getDefaultInstanceForType() {
            return datawave.annotation.protobuf.v1.TimeSpanSeconds.getDefaultInstance();
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.TimeSpanSeconds build() {
            datawave.annotation.protobuf.v1.TimeSpanSeconds result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.TimeSpanSeconds buildPartial() {
            datawave.annotation.protobuf.v1.TimeSpanSeconds result = new datawave.annotation.protobuf.v1.TimeSpanSeconds(this);
            result.start_ = start_;
            result.end_ = end_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof datawave.annotation.protobuf.v1.TimeSpanSeconds) {
                return mergeFrom((datawave.annotation.protobuf.v1.TimeSpanSeconds) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(datawave.annotation.protobuf.v1.TimeSpanSeconds other) {
            if (other == datawave.annotation.protobuf.v1.TimeSpanSeconds.getDefaultInstance())
                return this;
            if (other.getStart() != 0F) {
                setStart(other.getStart());
            }
            if (other.getEnd() != 0F) {
                setEnd(other.getEnd());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 13: {
                            start_ = input.readFloat();

                            break;
                        } // case 13
                        case 21: {
                            end_ = input.readFloat();

                            break;
                        } // case 21
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private float start_;

        /**
         * <code>float start = 1;</code>
         *
         * @return The start.
         */
        @java.lang.Override
        public float getStart() {
            return start_;
        }

        /**
         * <code>float start = 1;</code>
         *
         * @param value
         *            The start to set.
         * @return This builder for chaining.
         */
        public Builder setStart(float value) {

            start_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>float start = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStart() {

            start_ = 0F;
            onChanged();
            return this;
        }

        private float end_;

        /**
         * <code>float end = 2;</code>
         *
         * @return The end.
         */
        @java.lang.Override
        public float getEnd() {
            return end_;
        }

        /**
         * <code>float end = 2;</code>
         *
         * @param value
         *            The end to set.
         * @return This builder for chaining.
         */
        public Builder setEnd(float value) {

            end_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>float end = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearEnd() {

            end_ = 0F;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.v1.TimeSpanSeconds)
    }

    // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.v1.TimeSpanSeconds)
    private static final datawave.annotation.protobuf.v1.TimeSpanSeconds DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new datawave.annotation.protobuf.v1.TimeSpanSeconds();
    }

    public static datawave.annotation.protobuf.v1.TimeSpanSeconds getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeSpanSeconds> PARSER = new com.google.protobuf.AbstractParser<TimeSpanSeconds>() {
        @java.lang.Override
        public TimeSpanSeconds parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<TimeSpanSeconds> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeSpanSeconds> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public datawave.annotation.protobuf.v1.TimeSpanSeconds getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
