// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

public interface TimeSpanSecondsOrBuilder extends
                // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.v1.TimeSpanSeconds)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float start = 1;</code>
     *
     * @return The start.
     */
    float getStart();

    /**
     * <code>float end = 2;</code>
     *
     * @return The end.
     */
    float getEnd();
}
