// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Segment.proto

package datawave.annotation.protobuf;

public interface AnnotationProtobufOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.AnnotationProtobuf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string value = 1;</code>
   */
  boolean hasValue();
  /**
   * <code>required string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>required string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>required float score = 2;</code>
   */
  boolean hasScore();
  /**
   * <code>required float score = 2;</code>
   */
  float getScore();

  /**
   * <code>optional string ext = 3;</code>
   */
  boolean hasExt();
  /**
   * <code>optional string ext = 3;</code>
   */
  java.lang.String getExt();
  /**
   * <code>optional string ext = 3;</code>
   */
  com.google.protobuf.ByteString
      getExtBytes();
}
