// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Segment.proto

package datawave.annotation.protobuf;

/**
 * Protobuf enum {@code datawave.annotation.protobuf.BoundType}
 */
public enum BoundType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TIME_RANGE = 0;</code>
   */
  TIME_RANGE(0),
  /**
   * <code>POINTS = 1;</code>
   */
  POINTS(1),
  ;

  /**
   * <code>TIME_RANGE = 0;</code>
   */
  public static final int TIME_RANGE_VALUE = 0;
  /**
   * <code>POINTS = 1;</code>
   */
  public static final int POINTS_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BoundType valueOf(int value) {
    return forNumber(value);
  }

  public static BoundType forNumber(int value) {
    switch (value) {
      case 0: return TIME_RANGE;
      case 1: return POINTS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BoundType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BoundType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BoundType>() {
          public BoundType findValueByNumber(int number) {
            return BoundType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return datawave.annotation.protobuf.Segment.getDescriptor().getEnumTypes().get(0);
  }

  private static final BoundType[] VALUES = values();

  public static BoundType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BoundType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:datawave.annotation.protobuf.BoundType)
}

