// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Segment.proto

package datawave.annotation.protobuf;

/**
 * Protobuf type {@code datawave.annotation.protobuf.SegmentProtobuf}
 */
public  final class SegmentProtobuf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.SegmentProtobuf)
    SegmentProtobufOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SegmentProtobuf.newBuilder() to construct.
  private SegmentProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentProtobuf() {
    annotations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SegmentProtobuf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            datawave.annotation.protobuf.BoundsProtobuf.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = bounds_.toBuilder();
            }
            bounds_ = input.readMessage(datawave.annotation.protobuf.BoundsProtobuf.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bounds_);
              bounds_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              annotations_ = new java.util.ArrayList<datawave.annotation.protobuf.AnnotationProtobuf>();
              mutable_bitField0_ |= 0x00000002;
            }
            annotations_.add(
                input.readMessage(datawave.annotation.protobuf.AnnotationProtobuf.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        annotations_ = java.util.Collections.unmodifiableList(annotations_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentProtobuf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentProtobuf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datawave.annotation.protobuf.SegmentProtobuf.class, datawave.annotation.protobuf.SegmentProtobuf.Builder.class);
  }

  private int bitField0_;
  public static final int BOUNDS_FIELD_NUMBER = 1;
  private datawave.annotation.protobuf.BoundsProtobuf bounds_;
  /**
   * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
   */
  public boolean hasBounds() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
   */
  public datawave.annotation.protobuf.BoundsProtobuf getBounds() {
    return bounds_ == null ? datawave.annotation.protobuf.BoundsProtobuf.getDefaultInstance() : bounds_;
  }
  /**
   * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
   */
  public datawave.annotation.protobuf.BoundsProtobufOrBuilder getBoundsOrBuilder() {
    return bounds_ == null ? datawave.annotation.protobuf.BoundsProtobuf.getDefaultInstance() : bounds_;
  }

  public static final int ANNOTATIONS_FIELD_NUMBER = 2;
  private java.util.List<datawave.annotation.protobuf.AnnotationProtobuf> annotations_;
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  public java.util.List<datawave.annotation.protobuf.AnnotationProtobuf> getAnnotationsList() {
    return annotations_;
  }
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  public java.util.List<? extends datawave.annotation.protobuf.AnnotationProtobufOrBuilder> 
      getAnnotationsOrBuilderList() {
    return annotations_;
  }
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  public int getAnnotationsCount() {
    return annotations_.size();
  }
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  public datawave.annotation.protobuf.AnnotationProtobuf getAnnotations(int index) {
    return annotations_.get(index);
  }
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  public datawave.annotation.protobuf.AnnotationProtobufOrBuilder getAnnotationsOrBuilder(
      int index) {
    return annotations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasBounds()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBounds().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getAnnotationsCount(); i++) {
      if (!getAnnotations(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getBounds());
    }
    for (int i = 0; i < annotations_.size(); i++) {
      output.writeMessage(2, annotations_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBounds());
    }
    for (int i = 0; i < annotations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, annotations_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datawave.annotation.protobuf.SegmentProtobuf)) {
      return super.equals(obj);
    }
    datawave.annotation.protobuf.SegmentProtobuf other = (datawave.annotation.protobuf.SegmentProtobuf) obj;

    boolean result = true;
    result = result && (hasBounds() == other.hasBounds());
    if (hasBounds()) {
      result = result && getBounds()
          .equals(other.getBounds());
    }
    result = result && getAnnotationsList()
        .equals(other.getAnnotationsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBounds()) {
      hash = (37 * hash) + BOUNDS_FIELD_NUMBER;
      hash = (53 * hash) + getBounds().hashCode();
    }
    if (getAnnotationsCount() > 0) {
      hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getAnnotationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentProtobuf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datawave.annotation.protobuf.SegmentProtobuf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code datawave.annotation.protobuf.SegmentProtobuf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.SegmentProtobuf)
      datawave.annotation.protobuf.SegmentProtobufOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datawave.annotation.protobuf.SegmentProtobuf.class, datawave.annotation.protobuf.SegmentProtobuf.Builder.class);
    }

    // Construct using datawave.annotation.protobuf.SegmentProtobuf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBoundsFieldBuilder();
        getAnnotationsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (boundsBuilder_ == null) {
        bounds_ = null;
      } else {
        boundsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (annotationsBuilder_ == null) {
        annotations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        annotationsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentProtobuf_descriptor;
    }

    public datawave.annotation.protobuf.SegmentProtobuf getDefaultInstanceForType() {
      return datawave.annotation.protobuf.SegmentProtobuf.getDefaultInstance();
    }

    public datawave.annotation.protobuf.SegmentProtobuf build() {
      datawave.annotation.protobuf.SegmentProtobuf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public datawave.annotation.protobuf.SegmentProtobuf buildPartial() {
      datawave.annotation.protobuf.SegmentProtobuf result = new datawave.annotation.protobuf.SegmentProtobuf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (boundsBuilder_ == null) {
        result.bounds_ = bounds_;
      } else {
        result.bounds_ = boundsBuilder_.build();
      }
      if (annotationsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          annotations_ = java.util.Collections.unmodifiableList(annotations_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.annotations_ = annotations_;
      } else {
        result.annotations_ = annotationsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datawave.annotation.protobuf.SegmentProtobuf) {
        return mergeFrom((datawave.annotation.protobuf.SegmentProtobuf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datawave.annotation.protobuf.SegmentProtobuf other) {
      if (other == datawave.annotation.protobuf.SegmentProtobuf.getDefaultInstance()) return this;
      if (other.hasBounds()) {
        mergeBounds(other.getBounds());
      }
      if (annotationsBuilder_ == null) {
        if (!other.annotations_.isEmpty()) {
          if (annotations_.isEmpty()) {
            annotations_ = other.annotations_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAnnotationsIsMutable();
            annotations_.addAll(other.annotations_);
          }
          onChanged();
        }
      } else {
        if (!other.annotations_.isEmpty()) {
          if (annotationsBuilder_.isEmpty()) {
            annotationsBuilder_.dispose();
            annotationsBuilder_ = null;
            annotations_ = other.annotations_;
            bitField0_ = (bitField0_ & ~0x00000002);
            annotationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnnotationsFieldBuilder() : null;
          } else {
            annotationsBuilder_.addAllMessages(other.annotations_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasBounds()) {
        return false;
      }
      if (!getBounds().isInitialized()) {
        return false;
      }
      for (int i = 0; i < getAnnotationsCount(); i++) {
        if (!getAnnotations(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      datawave.annotation.protobuf.SegmentProtobuf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (datawave.annotation.protobuf.SegmentProtobuf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private datawave.annotation.protobuf.BoundsProtobuf bounds_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        datawave.annotation.protobuf.BoundsProtobuf, datawave.annotation.protobuf.BoundsProtobuf.Builder, datawave.annotation.protobuf.BoundsProtobufOrBuilder> boundsBuilder_;
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public boolean hasBounds() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public datawave.annotation.protobuf.BoundsProtobuf getBounds() {
      if (boundsBuilder_ == null) {
        return bounds_ == null ? datawave.annotation.protobuf.BoundsProtobuf.getDefaultInstance() : bounds_;
      } else {
        return boundsBuilder_.getMessage();
      }
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public Builder setBounds(datawave.annotation.protobuf.BoundsProtobuf value) {
      if (boundsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bounds_ = value;
        onChanged();
      } else {
        boundsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public Builder setBounds(
        datawave.annotation.protobuf.BoundsProtobuf.Builder builderForValue) {
      if (boundsBuilder_ == null) {
        bounds_ = builderForValue.build();
        onChanged();
      } else {
        boundsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public Builder mergeBounds(datawave.annotation.protobuf.BoundsProtobuf value) {
      if (boundsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            bounds_ != null &&
            bounds_ != datawave.annotation.protobuf.BoundsProtobuf.getDefaultInstance()) {
          bounds_ =
            datawave.annotation.protobuf.BoundsProtobuf.newBuilder(bounds_).mergeFrom(value).buildPartial();
        } else {
          bounds_ = value;
        }
        onChanged();
      } else {
        boundsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public Builder clearBounds() {
      if (boundsBuilder_ == null) {
        bounds_ = null;
        onChanged();
      } else {
        boundsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public datawave.annotation.protobuf.BoundsProtobuf.Builder getBoundsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBoundsFieldBuilder().getBuilder();
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    public datawave.annotation.protobuf.BoundsProtobufOrBuilder getBoundsOrBuilder() {
      if (boundsBuilder_ != null) {
        return boundsBuilder_.getMessageOrBuilder();
      } else {
        return bounds_ == null ?
            datawave.annotation.protobuf.BoundsProtobuf.getDefaultInstance() : bounds_;
      }
    }
    /**
     * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        datawave.annotation.protobuf.BoundsProtobuf, datawave.annotation.protobuf.BoundsProtobuf.Builder, datawave.annotation.protobuf.BoundsProtobufOrBuilder> 
        getBoundsFieldBuilder() {
      if (boundsBuilder_ == null) {
        boundsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            datawave.annotation.protobuf.BoundsProtobuf, datawave.annotation.protobuf.BoundsProtobuf.Builder, datawave.annotation.protobuf.BoundsProtobufOrBuilder>(
                getBounds(),
                getParentForChildren(),
                isClean());
        bounds_ = null;
      }
      return boundsBuilder_;
    }

    private java.util.List<datawave.annotation.protobuf.AnnotationProtobuf> annotations_ =
      java.util.Collections.emptyList();
    private void ensureAnnotationsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        annotations_ = new java.util.ArrayList<datawave.annotation.protobuf.AnnotationProtobuf>(annotations_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        datawave.annotation.protobuf.AnnotationProtobuf, datawave.annotation.protobuf.AnnotationProtobuf.Builder, datawave.annotation.protobuf.AnnotationProtobufOrBuilder> annotationsBuilder_;

    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public java.util.List<datawave.annotation.protobuf.AnnotationProtobuf> getAnnotationsList() {
      if (annotationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(annotations_);
      } else {
        return annotationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public int getAnnotationsCount() {
      if (annotationsBuilder_ == null) {
        return annotations_.size();
      } else {
        return annotationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public datawave.annotation.protobuf.AnnotationProtobuf getAnnotations(int index) {
      if (annotationsBuilder_ == null) {
        return annotations_.get(index);
      } else {
        return annotationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder setAnnotations(
        int index, datawave.annotation.protobuf.AnnotationProtobuf value) {
      if (annotationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnotationsIsMutable();
        annotations_.set(index, value);
        onChanged();
      } else {
        annotationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder setAnnotations(
        int index, datawave.annotation.protobuf.AnnotationProtobuf.Builder builderForValue) {
      if (annotationsBuilder_ == null) {
        ensureAnnotationsIsMutable();
        annotations_.set(index, builderForValue.build());
        onChanged();
      } else {
        annotationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder addAnnotations(datawave.annotation.protobuf.AnnotationProtobuf value) {
      if (annotationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnotationsIsMutable();
        annotations_.add(value);
        onChanged();
      } else {
        annotationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder addAnnotations(
        int index, datawave.annotation.protobuf.AnnotationProtobuf value) {
      if (annotationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnnotationsIsMutable();
        annotations_.add(index, value);
        onChanged();
      } else {
        annotationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder addAnnotations(
        datawave.annotation.protobuf.AnnotationProtobuf.Builder builderForValue) {
      if (annotationsBuilder_ == null) {
        ensureAnnotationsIsMutable();
        annotations_.add(builderForValue.build());
        onChanged();
      } else {
        annotationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder addAnnotations(
        int index, datawave.annotation.protobuf.AnnotationProtobuf.Builder builderForValue) {
      if (annotationsBuilder_ == null) {
        ensureAnnotationsIsMutable();
        annotations_.add(index, builderForValue.build());
        onChanged();
      } else {
        annotationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder addAllAnnotations(
        java.lang.Iterable<? extends datawave.annotation.protobuf.AnnotationProtobuf> values) {
      if (annotationsBuilder_ == null) {
        ensureAnnotationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, annotations_);
        onChanged();
      } else {
        annotationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder clearAnnotations() {
      if (annotationsBuilder_ == null) {
        annotations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        annotationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public Builder removeAnnotations(int index) {
      if (annotationsBuilder_ == null) {
        ensureAnnotationsIsMutable();
        annotations_.remove(index);
        onChanged();
      } else {
        annotationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public datawave.annotation.protobuf.AnnotationProtobuf.Builder getAnnotationsBuilder(
        int index) {
      return getAnnotationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public datawave.annotation.protobuf.AnnotationProtobufOrBuilder getAnnotationsOrBuilder(
        int index) {
      if (annotationsBuilder_ == null) {
        return annotations_.get(index);  } else {
        return annotationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public java.util.List<? extends datawave.annotation.protobuf.AnnotationProtobufOrBuilder> 
         getAnnotationsOrBuilderList() {
      if (annotationsBuilder_ != null) {
        return annotationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(annotations_);
      }
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public datawave.annotation.protobuf.AnnotationProtobuf.Builder addAnnotationsBuilder() {
      return getAnnotationsFieldBuilder().addBuilder(
          datawave.annotation.protobuf.AnnotationProtobuf.getDefaultInstance());
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public datawave.annotation.protobuf.AnnotationProtobuf.Builder addAnnotationsBuilder(
        int index) {
      return getAnnotationsFieldBuilder().addBuilder(
          index, datawave.annotation.protobuf.AnnotationProtobuf.getDefaultInstance());
    }
    /**
     * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
     */
    public java.util.List<datawave.annotation.protobuf.AnnotationProtobuf.Builder> 
         getAnnotationsBuilderList() {
      return getAnnotationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        datawave.annotation.protobuf.AnnotationProtobuf, datawave.annotation.protobuf.AnnotationProtobuf.Builder, datawave.annotation.protobuf.AnnotationProtobufOrBuilder> 
        getAnnotationsFieldBuilder() {
      if (annotationsBuilder_ == null) {
        annotationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            datawave.annotation.protobuf.AnnotationProtobuf, datawave.annotation.protobuf.AnnotationProtobuf.Builder, datawave.annotation.protobuf.AnnotationProtobufOrBuilder>(
                annotations_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        annotations_ = null;
      }
      return annotationsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.SegmentProtobuf)
  }

  // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.SegmentProtobuf)
  private static final datawave.annotation.protobuf.SegmentProtobuf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datawave.annotation.protobuf.SegmentProtobuf();
  }

  public static datawave.annotation.protobuf.SegmentProtobuf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SegmentProtobuf>
      PARSER = new com.google.protobuf.AbstractParser<SegmentProtobuf>() {
    public SegmentProtobuf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SegmentProtobuf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SegmentProtobuf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentProtobuf> getParserForType() {
    return PARSER;
  }

  public datawave.annotation.protobuf.SegmentProtobuf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

