// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/SegmentPB.proto

package datawave.annotation.protobuf;

public interface SegmentDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.SegmentData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
   */
  boolean hasBoundary();
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
   */
  datawave.annotation.protobuf.SegmentBoundary getBoundary();
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
   */
  datawave.annotation.protobuf.SegmentBoundaryOrBuilder getBoundaryOrBuilder();

  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  java.util.List<datawave.annotation.protobuf.SegmentValue> 
      getValueList();
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  datawave.annotation.protobuf.SegmentValue getValue(int index);
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  int getValueCount();
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  java.util.List<? extends datawave.annotation.protobuf.SegmentValueOrBuilder> 
      getValueOrBuilderList();
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  datawave.annotation.protobuf.SegmentValueOrBuilder getValueOrBuilder(
      int index);
}
