// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/Segment.proto

package datawave.annotation.protobuf;

public interface SegmentBoundaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.SegmentBoundary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
   */
  boolean hasType();
  /**
   * <code>required .datawave.annotation.protobuf.SegmentBoundaryType type = 1;</code>
   */
  datawave.annotation.protobuf.SegmentBoundaryType getType();

  /**
   * <code>required string start = 2;</code>
   */
  boolean hasStart();
  /**
   * <code>required string start = 2;</code>
   */
  java.lang.String getStart();
  /**
   * <code>required string start = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartBytes();

  /**
   * <code>required string end = 3;</code>
   */
  boolean hasEnd();
  /**
   * <code>required string end = 3;</code>
   */
  java.lang.String getEnd();
  /**
   * <code>required string end = 3;</code>
   */
  com.google.protobuf.ByteString
      getEndBytes();

  /**
   * <code>optional uint32 rotation = 4;</code>
   */
  boolean hasRotation();
  /**
   * <code>optional uint32 rotation = 4;</code>
   */
  int getRotation();
}
