// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/SegmentPB.proto

package datawave.annotation.protobuf;

public interface SegmentValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.SegmentValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the value associated with this segment.
   * </pre>
   *
   * <code>required string value = 1;</code>
   */
  boolean hasValue();
  /**
   * <pre>
   * the value associated with this segment.
   * </pre>
   *
   * <code>required string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * the value associated with this segment.
   * </pre>
   *
   * <code>required string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <pre>
   * the score associated with this value (e.g., confidence)
   * </pre>
   *
   * <code>required float score = 2;</code>
   */
  boolean hasScore();
  /**
   * <pre>
   * the score associated with this value (e.g., confidence)
   * </pre>
   *
   * <code>required float score = 2;</code>
   */
  float getScore();

  /**
   * <pre>
   * an optional extension providing additional data.
   * </pre>
   *
   * <code>optional string extension = 3;</code>
   */
  boolean hasExtension();
  /**
   * <pre>
   * an optional extension providing additional data.
   * </pre>
   *
   * <code>optional string extension = 3;</code>
   */
  java.lang.String getExtension();
  /**
   * <pre>
   * an optional extension providing additional data.
   * </pre>
   *
   * <code>optional string extension = 3;</code>
   */
  com.google.protobuf.ByteString
      getExtensionBytes();
}
