// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/Segment.proto

package datawave.annotation.protobuf;

/**
 * <pre>
 * Segment Data stored in the Accumulo value
 * </pre>
 *
 * Protobuf type {@code datawave.annotation.protobuf.SegmentData}
 */
public  final class SegmentData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.SegmentData)
    SegmentDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SegmentData.newBuilder() to construct.
  private SegmentData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentData() {
    values_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SegmentData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            datawave.annotation.protobuf.SegmentBoundary.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = bounds_.toBuilder();
            }
            bounds_ = input.readMessage(datawave.annotation.protobuf.SegmentBoundary.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bounds_);
              bounds_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              values_ = new java.util.ArrayList<datawave.annotation.protobuf.SegmentValue>();
              mutable_bitField0_ |= 0x00000002;
            }
            values_.add(
                input.readMessage(datawave.annotation.protobuf.SegmentValue.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        values_ = java.util.Collections.unmodifiableList(values_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datawave.annotation.protobuf.SegmentData.class, datawave.annotation.protobuf.SegmentData.Builder.class);
  }

  private int bitField0_;
  public static final int BOUNDS_FIELD_NUMBER = 1;
  private datawave.annotation.protobuf.SegmentBoundary bounds_;
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
   */
  public boolean hasBounds() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
   */
  public datawave.annotation.protobuf.SegmentBoundary getBounds() {
    return bounds_ == null ? datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : bounds_;
  }
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
   */
  public datawave.annotation.protobuf.SegmentBoundaryOrBuilder getBoundsOrBuilder() {
    return bounds_ == null ? datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : bounds_;
  }

  public static final int VALUES_FIELD_NUMBER = 2;
  private java.util.List<datawave.annotation.protobuf.SegmentValue> values_;
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
   */
  public java.util.List<datawave.annotation.protobuf.SegmentValue> getValuesList() {
    return values_;
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
   */
  public java.util.List<? extends datawave.annotation.protobuf.SegmentValueOrBuilder> 
      getValuesOrBuilderList() {
    return values_;
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
   */
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
   */
  public datawave.annotation.protobuf.SegmentValue getValues(int index) {
    return values_.get(index);
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
   */
  public datawave.annotation.protobuf.SegmentValueOrBuilder getValuesOrBuilder(
      int index) {
    return values_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasBounds()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBounds().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getValuesCount(); i++) {
      if (!getValues(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getBounds());
    }
    for (int i = 0; i < values_.size(); i++) {
      output.writeMessage(2, values_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBounds());
    }
    for (int i = 0; i < values_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, values_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datawave.annotation.protobuf.SegmentData)) {
      return super.equals(obj);
    }
    datawave.annotation.protobuf.SegmentData other = (datawave.annotation.protobuf.SegmentData) obj;

    boolean result = true;
    result = result && (hasBounds() == other.hasBounds());
    if (hasBounds()) {
      result = result && getBounds()
          .equals(other.getBounds());
    }
    result = result && getValuesList()
        .equals(other.getValuesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBounds()) {
      hash = (37 * hash) + BOUNDS_FIELD_NUMBER;
      hash = (53 * hash) + getBounds().hashCode();
    }
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datawave.annotation.protobuf.SegmentData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datawave.annotation.protobuf.SegmentData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Segment Data stored in the Accumulo value
   * </pre>
   *
   * Protobuf type {@code datawave.annotation.protobuf.SegmentData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.SegmentData)
      datawave.annotation.protobuf.SegmentDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datawave.annotation.protobuf.SegmentData.class, datawave.annotation.protobuf.SegmentData.Builder.class);
    }

    // Construct using datawave.annotation.protobuf.SegmentData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBoundsFieldBuilder();
        getValuesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (boundsBuilder_ == null) {
        bounds_ = null;
      } else {
        boundsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        valuesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentData_descriptor;
    }

    public datawave.annotation.protobuf.SegmentData getDefaultInstanceForType() {
      return datawave.annotation.protobuf.SegmentData.getDefaultInstance();
    }

    public datawave.annotation.protobuf.SegmentData build() {
      datawave.annotation.protobuf.SegmentData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public datawave.annotation.protobuf.SegmentData buildPartial() {
      datawave.annotation.protobuf.SegmentData result = new datawave.annotation.protobuf.SegmentData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (boundsBuilder_ == null) {
        result.bounds_ = bounds_;
      } else {
        result.bounds_ = boundsBuilder_.build();
      }
      if (valuesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.values_ = values_;
      } else {
        result.values_ = valuesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datawave.annotation.protobuf.SegmentData) {
        return mergeFrom((datawave.annotation.protobuf.SegmentData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datawave.annotation.protobuf.SegmentData other) {
      if (other == datawave.annotation.protobuf.SegmentData.getDefaultInstance()) return this;
      if (other.hasBounds()) {
        mergeBounds(other.getBounds());
      }
      if (valuesBuilder_ == null) {
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
      } else {
        if (!other.values_.isEmpty()) {
          if (valuesBuilder_.isEmpty()) {
            valuesBuilder_.dispose();
            valuesBuilder_ = null;
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
            valuesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValuesFieldBuilder() : null;
          } else {
            valuesBuilder_.addAllMessages(other.values_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasBounds()) {
        return false;
      }
      if (!getBounds().isInitialized()) {
        return false;
      }
      for (int i = 0; i < getValuesCount(); i++) {
        if (!getValues(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      datawave.annotation.protobuf.SegmentData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (datawave.annotation.protobuf.SegmentData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private datawave.annotation.protobuf.SegmentBoundary bounds_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        datawave.annotation.protobuf.SegmentBoundary, datawave.annotation.protobuf.SegmentBoundary.Builder, datawave.annotation.protobuf.SegmentBoundaryOrBuilder> boundsBuilder_;
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public boolean hasBounds() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public datawave.annotation.protobuf.SegmentBoundary getBounds() {
      if (boundsBuilder_ == null) {
        return bounds_ == null ? datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : bounds_;
      } else {
        return boundsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public Builder setBounds(datawave.annotation.protobuf.SegmentBoundary value) {
      if (boundsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bounds_ = value;
        onChanged();
      } else {
        boundsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public Builder setBounds(
        datawave.annotation.protobuf.SegmentBoundary.Builder builderForValue) {
      if (boundsBuilder_ == null) {
        bounds_ = builderForValue.build();
        onChanged();
      } else {
        boundsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public Builder mergeBounds(datawave.annotation.protobuf.SegmentBoundary value) {
      if (boundsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            bounds_ != null &&
            bounds_ != datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance()) {
          bounds_ =
            datawave.annotation.protobuf.SegmentBoundary.newBuilder(bounds_).mergeFrom(value).buildPartial();
        } else {
          bounds_ = value;
        }
        onChanged();
      } else {
        boundsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public Builder clearBounds() {
      if (boundsBuilder_ == null) {
        bounds_ = null;
        onChanged();
      } else {
        boundsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public datawave.annotation.protobuf.SegmentBoundary.Builder getBoundsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBoundsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    public datawave.annotation.protobuf.SegmentBoundaryOrBuilder getBoundsOrBuilder() {
      if (boundsBuilder_ != null) {
        return boundsBuilder_.getMessageOrBuilder();
      } else {
        return bounds_ == null ?
            datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : bounds_;
      }
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary bounds = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        datawave.annotation.protobuf.SegmentBoundary, datawave.annotation.protobuf.SegmentBoundary.Builder, datawave.annotation.protobuf.SegmentBoundaryOrBuilder> 
        getBoundsFieldBuilder() {
      if (boundsBuilder_ == null) {
        boundsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            datawave.annotation.protobuf.SegmentBoundary, datawave.annotation.protobuf.SegmentBoundary.Builder, datawave.annotation.protobuf.SegmentBoundaryOrBuilder>(
                getBounds(),
                getParentForChildren(),
                isClean());
        bounds_ = null;
      }
      return boundsBuilder_;
    }

    private java.util.List<datawave.annotation.protobuf.SegmentValue> values_ =
      java.util.Collections.emptyList();
    private void ensureValuesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        values_ = new java.util.ArrayList<datawave.annotation.protobuf.SegmentValue>(values_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        datawave.annotation.protobuf.SegmentValue, datawave.annotation.protobuf.SegmentValue.Builder, datawave.annotation.protobuf.SegmentValueOrBuilder> valuesBuilder_;

    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public java.util.List<datawave.annotation.protobuf.SegmentValue> getValuesList() {
      if (valuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(values_);
      } else {
        return valuesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public int getValuesCount() {
      if (valuesBuilder_ == null) {
        return values_.size();
      } else {
        return valuesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue getValues(int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);
      } else {
        return valuesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder setValues(
        int index, datawave.annotation.protobuf.SegmentValue value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder setValues(
        int index, datawave.annotation.protobuf.SegmentValue.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.set(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder addValues(datawave.annotation.protobuf.SegmentValue value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder addValues(
        int index, datawave.annotation.protobuf.SegmentValue value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(index, value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder addValues(
        datawave.annotation.protobuf.SegmentValue.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder addValues(
        int index, datawave.annotation.protobuf.SegmentValue.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder addAllValues(
        java.lang.Iterable<? extends datawave.annotation.protobuf.SegmentValue> values) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
      } else {
        valuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder clearValues() {
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        valuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public Builder removeValues(int index) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.remove(index);
        onChanged();
      } else {
        valuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue.Builder getValuesBuilder(
        int index) {
      return getValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValueOrBuilder getValuesOrBuilder(
        int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);  } else {
        return valuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public java.util.List<? extends datawave.annotation.protobuf.SegmentValueOrBuilder> 
         getValuesOrBuilderList() {
      if (valuesBuilder_ != null) {
        return valuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(values_);
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue.Builder addValuesBuilder() {
      return getValuesFieldBuilder().addBuilder(
          datawave.annotation.protobuf.SegmentValue.getDefaultInstance());
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue.Builder addValuesBuilder(
        int index) {
      return getValuesFieldBuilder().addBuilder(
          index, datawave.annotation.protobuf.SegmentValue.getDefaultInstance());
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue values = 2;</code>
     */
    public java.util.List<datawave.annotation.protobuf.SegmentValue.Builder> 
         getValuesBuilderList() {
      return getValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        datawave.annotation.protobuf.SegmentValue, datawave.annotation.protobuf.SegmentValue.Builder, datawave.annotation.protobuf.SegmentValueOrBuilder> 
        getValuesFieldBuilder() {
      if (valuesBuilder_ == null) {
        valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            datawave.annotation.protobuf.SegmentValue, datawave.annotation.protobuf.SegmentValue.Builder, datawave.annotation.protobuf.SegmentValueOrBuilder>(
                values_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      return valuesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.SegmentData)
  }

  // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.SegmentData)
  private static final datawave.annotation.protobuf.SegmentData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datawave.annotation.protobuf.SegmentData();
  }

  public static datawave.annotation.protobuf.SegmentData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SegmentData>
      PARSER = new com.google.protobuf.AbstractParser<SegmentData>() {
    public SegmentData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SegmentData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SegmentData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentData> getParserForType() {
    return PARSER;
  }

  public datawave.annotation.protobuf.SegmentData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

