// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/Segment.proto

package datawave.annotation.protobuf;

public final class Segment {
  private Segment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datawave_annotation_protobuf_SegmentBoundary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datawave_annotation_protobuf_SegmentBoundary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datawave_annotation_protobuf_SegmentValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datawave_annotation_protobuf_SegmentValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datawave_annotation_protobuf_SegmentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datawave_annotation_protobuf_SegmentData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/Segment.proto\022\034dataw" +
      "ave.annotation.protobuf\"\200\001\n\017SegmentBound" +
      "ary\022?\n\004type\030\001 \002(\01621.datawave.annotation." +
      "protobuf.SegmentBoundaryType\022\r\n\005start\030\002 " +
      "\002(\t\022\013\n\003end\030\003 \002(\t\022\020\n\010rotation\030\004 \001(\r\"?\n\014Se" +
      "gmentValue\022\r\n\005value\030\001 \002(\t\022\r\n\005score\030\002 \002(\002" +
      "\022\021\n\textension\030\003 \001(\t\"\210\001\n\013SegmentData\022=\n\006b" +
      "ounds\030\001 \002(\0132-.datawave.annotation.protob" +
      "uf.SegmentBoundary\022:\n\006values\030\002 \003(\0132*.dat" +
      "awave.annotation.protobuf.SegmentValue*-" +
      "\n\023SegmentBoundaryType\022\010\n\004TIME\020\000\022\014\n\010POSIT" +
      "ION\020\001B\"\n\034datawave.annotation.protobufH\001P" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datawave_annotation_protobuf_SegmentBoundary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datawave_annotation_protobuf_SegmentBoundary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datawave_annotation_protobuf_SegmentBoundary_descriptor,
        new java.lang.String[] { "Type", "Start", "End", "Rotation", });
    internal_static_datawave_annotation_protobuf_SegmentValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datawave_annotation_protobuf_SegmentValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datawave_annotation_protobuf_SegmentValue_descriptor,
        new java.lang.String[] { "Value", "Score", "Extension", });
    internal_static_datawave_annotation_protobuf_SegmentData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datawave_annotation_protobuf_SegmentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datawave_annotation_protobuf_SegmentData_descriptor,
        new java.lang.String[] { "Bounds", "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
