// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Segment.proto

package datawave.annotation.protobuf;

public interface SegmentProtobufOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.SegmentProtobuf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
   */
  boolean hasBounds();
  /**
   * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
   */
  datawave.annotation.protobuf.BoundsProtobuf getBounds();
  /**
   * <code>required .datawave.annotation.protobuf.BoundsProtobuf bounds = 1;</code>
   */
  datawave.annotation.protobuf.BoundsProtobufOrBuilder getBoundsOrBuilder();

  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  java.util.List<datawave.annotation.protobuf.AnnotationProtobuf> 
      getAnnotationsList();
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  datawave.annotation.protobuf.AnnotationProtobuf getAnnotations(int index);
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  int getAnnotationsCount();
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  java.util.List<? extends datawave.annotation.protobuf.AnnotationProtobufOrBuilder> 
      getAnnotationsOrBuilderList();
  /**
   * <code>repeated .datawave.annotation.protobuf.AnnotationProtobuf annotations = 2;</code>
   */
  datawave.annotation.protobuf.AnnotationProtobufOrBuilder getAnnotationsOrBuilder(
      int index);
}
