// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Segment.proto

package datawave.annotation.protobuf;

public final class Segment {
  private Segment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datawave_annotation_protobuf_BoundsProtobuf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datawave_annotation_protobuf_BoundsProtobuf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datawave_annotation_protobuf_AnnotationProtobuf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datawave_annotation_protobuf_AnnotationProtobuf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datawave_annotation_protobuf_SegmentProtobuf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datawave_annotation_protobuf_SegmentProtobuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rSegment.proto\022\034datawave.annotation.pro" +
      "tobuf\"u\n\016BoundsProtobuf\0225\n\004type\030\001 \002(\0162\'." +
      "datawave.annotation.protobuf.BoundType\022\r" +
      "\n\005start\030\002 \002(\t\022\013\n\003end\030\003 \002(\t\022\020\n\010rotation\030\004" +
      " \001(\r\"?\n\022AnnotationProtobuf\022\r\n\005value\030\001 \002(" +
      "\t\022\r\n\005score\030\002 \002(\002\022\013\n\003ext\030\003 \001(\t\"\226\001\n\017Segmen" +
      "tProtobuf\022<\n\006bounds\030\001 \002(\0132,.datawave.ann" +
      "otation.protobuf.BoundsProtobuf\022E\n\013annot" +
      "ations\030\002 \003(\01320.datawave.annotation.proto" +
      "buf.AnnotationProtobuf*\'\n\tBoundType\022\016\n\nT" +
      "IME_RANGE\020\000\022\n\n\006POINTS\020\001B\"\n\034datawave.anno" +
      "tation.protobufH\001P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datawave_annotation_protobuf_BoundsProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datawave_annotation_protobuf_BoundsProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datawave_annotation_protobuf_BoundsProtobuf_descriptor,
        new java.lang.String[] { "Type", "Start", "End", "Rotation", });
    internal_static_datawave_annotation_protobuf_AnnotationProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datawave_annotation_protobuf_AnnotationProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datawave_annotation_protobuf_AnnotationProtobuf_descriptor,
        new java.lang.String[] { "Value", "Score", "Ext", });
    internal_static_datawave_annotation_protobuf_SegmentProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datawave_annotation_protobuf_SegmentProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datawave_annotation_protobuf_SegmentProtobuf_descriptor,
        new java.lang.String[] { "Bounds", "Annotations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
