// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/SegmentPB.proto

package datawave.annotation.protobuf;

/**
 * <pre>
 * Segment Data stored in the Accumulo value
 * </pre>
 *
 * Protobuf type {@code datawave.annotation.protobuf.SegmentData}
 */
public  final class SegmentData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.SegmentData)
    SegmentDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SegmentData.newBuilder() to construct.
  private SegmentData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentData() {
    value_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SegmentData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            datawave.annotation.protobuf.SegmentBoundary.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = boundary_.toBuilder();
            }
            boundary_ = input.readMessage(datawave.annotation.protobuf.SegmentBoundary.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(boundary_);
              boundary_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              value_ = new java.util.ArrayList<datawave.annotation.protobuf.SegmentValue>();
              mutable_bitField0_ |= 0x00000002;
            }
            value_.add(
                input.readMessage(datawave.annotation.protobuf.SegmentValue.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        value_ = java.util.Collections.unmodifiableList(value_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datawave.annotation.protobuf.SegmentData.class, datawave.annotation.protobuf.SegmentData.Builder.class);
  }

  private int bitField0_;
  public static final int BOUNDARY_FIELD_NUMBER = 1;
  private datawave.annotation.protobuf.SegmentBoundary boundary_;
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
   */
  public boolean hasBoundary() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
   */
  public datawave.annotation.protobuf.SegmentBoundary getBoundary() {
    return boundary_ == null ? datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : boundary_;
  }
  /**
   * <pre>
   * the boundary for this segment.
   * </pre>
   *
   * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
   */
  public datawave.annotation.protobuf.SegmentBoundaryOrBuilder getBoundaryOrBuilder() {
    return boundary_ == null ? datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : boundary_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private java.util.List<datawave.annotation.protobuf.SegmentValue> value_;
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  public java.util.List<datawave.annotation.protobuf.SegmentValue> getValueList() {
    return value_;
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  public java.util.List<? extends datawave.annotation.protobuf.SegmentValueOrBuilder> 
      getValueOrBuilderList() {
    return value_;
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  public int getValueCount() {
    return value_.size();
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  public datawave.annotation.protobuf.SegmentValue getValue(int index) {
    return value_.get(index);
  }
  /**
   * <pre>
   * values associated with this segment.
   * </pre>
   *
   * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
   */
  public datawave.annotation.protobuf.SegmentValueOrBuilder getValueOrBuilder(
      int index) {
    return value_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasBoundary()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBoundary().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getValueCount(); i++) {
      if (!getValue(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getBoundary());
    }
    for (int i = 0; i < value_.size(); i++) {
      output.writeMessage(2, value_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBoundary());
    }
    for (int i = 0; i < value_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, value_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datawave.annotation.protobuf.SegmentData)) {
      return super.equals(obj);
    }
    datawave.annotation.protobuf.SegmentData other = (datawave.annotation.protobuf.SegmentData) obj;

    boolean result = true;
    result = result && (hasBoundary() == other.hasBoundary());
    if (hasBoundary()) {
      result = result && getBoundary()
          .equals(other.getBoundary());
    }
    result = result && getValueList()
        .equals(other.getValueList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBoundary()) {
      hash = (37 * hash) + BOUNDARY_FIELD_NUMBER;
      hash = (53 * hash) + getBoundary().hashCode();
    }
    if (getValueCount() > 0) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValueList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datawave.annotation.protobuf.SegmentData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datawave.annotation.protobuf.SegmentData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Segment Data stored in the Accumulo value
   * </pre>
   *
   * Protobuf type {@code datawave.annotation.protobuf.SegmentData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.SegmentData)
      datawave.annotation.protobuf.SegmentDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datawave.annotation.protobuf.SegmentData.class, datawave.annotation.protobuf.SegmentData.Builder.class);
    }

    // Construct using datawave.annotation.protobuf.SegmentData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBoundaryFieldBuilder();
        getValueFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (boundaryBuilder_ == null) {
        boundary_ = null;
      } else {
        boundaryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (valueBuilder_ == null) {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        valueBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datawave.annotation.protobuf.SegmentPB.internal_static_datawave_annotation_protobuf_SegmentData_descriptor;
    }

    public datawave.annotation.protobuf.SegmentData getDefaultInstanceForType() {
      return datawave.annotation.protobuf.SegmentData.getDefaultInstance();
    }

    public datawave.annotation.protobuf.SegmentData build() {
      datawave.annotation.protobuf.SegmentData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public datawave.annotation.protobuf.SegmentData buildPartial() {
      datawave.annotation.protobuf.SegmentData result = new datawave.annotation.protobuf.SegmentData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (boundaryBuilder_ == null) {
        result.boundary_ = boundary_;
      } else {
        result.boundary_ = boundaryBuilder_.build();
      }
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datawave.annotation.protobuf.SegmentData) {
        return mergeFrom((datawave.annotation.protobuf.SegmentData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datawave.annotation.protobuf.SegmentData other) {
      if (other == datawave.annotation.protobuf.SegmentData.getDefaultInstance()) return this;
      if (other.hasBoundary()) {
        mergeBoundary(other.getBoundary());
      }
      if (valueBuilder_ == null) {
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
      } else {
        if (!other.value_.isEmpty()) {
          if (valueBuilder_.isEmpty()) {
            valueBuilder_.dispose();
            valueBuilder_ = null;
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000002);
            valueBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValueFieldBuilder() : null;
          } else {
            valueBuilder_.addAllMessages(other.value_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasBoundary()) {
        return false;
      }
      if (!getBoundary().isInitialized()) {
        return false;
      }
      for (int i = 0; i < getValueCount(); i++) {
        if (!getValue(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      datawave.annotation.protobuf.SegmentData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (datawave.annotation.protobuf.SegmentData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private datawave.annotation.protobuf.SegmentBoundary boundary_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        datawave.annotation.protobuf.SegmentBoundary, datawave.annotation.protobuf.SegmentBoundary.Builder, datawave.annotation.protobuf.SegmentBoundaryOrBuilder> boundaryBuilder_;
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public boolean hasBoundary() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public datawave.annotation.protobuf.SegmentBoundary getBoundary() {
      if (boundaryBuilder_ == null) {
        return boundary_ == null ? datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : boundary_;
      } else {
        return boundaryBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public Builder setBoundary(datawave.annotation.protobuf.SegmentBoundary value) {
      if (boundaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        boundary_ = value;
        onChanged();
      } else {
        boundaryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public Builder setBoundary(
        datawave.annotation.protobuf.SegmentBoundary.Builder builderForValue) {
      if (boundaryBuilder_ == null) {
        boundary_ = builderForValue.build();
        onChanged();
      } else {
        boundaryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public Builder mergeBoundary(datawave.annotation.protobuf.SegmentBoundary value) {
      if (boundaryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            boundary_ != null &&
            boundary_ != datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance()) {
          boundary_ =
            datawave.annotation.protobuf.SegmentBoundary.newBuilder(boundary_).mergeFrom(value).buildPartial();
        } else {
          boundary_ = value;
        }
        onChanged();
      } else {
        boundaryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public Builder clearBoundary() {
      if (boundaryBuilder_ == null) {
        boundary_ = null;
        onChanged();
      } else {
        boundaryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public datawave.annotation.protobuf.SegmentBoundary.Builder getBoundaryBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBoundaryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    public datawave.annotation.protobuf.SegmentBoundaryOrBuilder getBoundaryOrBuilder() {
      if (boundaryBuilder_ != null) {
        return boundaryBuilder_.getMessageOrBuilder();
      } else {
        return boundary_ == null ?
            datawave.annotation.protobuf.SegmentBoundary.getDefaultInstance() : boundary_;
      }
    }
    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>required .datawave.annotation.protobuf.SegmentBoundary boundary = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        datawave.annotation.protobuf.SegmentBoundary, datawave.annotation.protobuf.SegmentBoundary.Builder, datawave.annotation.protobuf.SegmentBoundaryOrBuilder> 
        getBoundaryFieldBuilder() {
      if (boundaryBuilder_ == null) {
        boundaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            datawave.annotation.protobuf.SegmentBoundary, datawave.annotation.protobuf.SegmentBoundary.Builder, datawave.annotation.protobuf.SegmentBoundaryOrBuilder>(
                getBoundary(),
                getParentForChildren(),
                isClean());
        boundary_ = null;
      }
      return boundaryBuilder_;
    }

    private java.util.List<datawave.annotation.protobuf.SegmentValue> value_ =
      java.util.Collections.emptyList();
    private void ensureValueIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        value_ = new java.util.ArrayList<datawave.annotation.protobuf.SegmentValue>(value_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        datawave.annotation.protobuf.SegmentValue, datawave.annotation.protobuf.SegmentValue.Builder, datawave.annotation.protobuf.SegmentValueOrBuilder> valueBuilder_;

    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public java.util.List<datawave.annotation.protobuf.SegmentValue> getValueList() {
      if (valueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(value_);
      } else {
        return valueBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public int getValueCount() {
      if (valueBuilder_ == null) {
        return value_.size();
      } else {
        return valueBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue getValue(int index) {
      if (valueBuilder_ == null) {
        return value_.get(index);
      } else {
        return valueBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder setValue(
        int index, datawave.annotation.protobuf.SegmentValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
      } else {
        valueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder setValue(
        int index, datawave.annotation.protobuf.SegmentValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.set(index, builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder addValue(datawave.annotation.protobuf.SegmentValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
      } else {
        valueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder addValue(
        int index, datawave.annotation.protobuf.SegmentValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.add(index, value);
        onChanged();
      } else {
        valueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder addValue(
        datawave.annotation.protobuf.SegmentValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.add(builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder addValue(
        int index, datawave.annotation.protobuf.SegmentValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.add(index, builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder addAllValue(
        java.lang.Iterable<? extends datawave.annotation.protobuf.SegmentValue> values) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
      } else {
        valueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        valueBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public Builder removeValue(int index) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.remove(index);
        onChanged();
      } else {
        valueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue.Builder getValueBuilder(
        int index) {
      return getValueFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValueOrBuilder getValueOrBuilder(
        int index) {
      if (valueBuilder_ == null) {
        return value_.get(index);  } else {
        return valueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public java.util.List<? extends datawave.annotation.protobuf.SegmentValueOrBuilder> 
         getValueOrBuilderList() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(value_);
      }
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue.Builder addValueBuilder() {
      return getValueFieldBuilder().addBuilder(
          datawave.annotation.protobuf.SegmentValue.getDefaultInstance());
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public datawave.annotation.protobuf.SegmentValue.Builder addValueBuilder(
        int index) {
      return getValueFieldBuilder().addBuilder(
          index, datawave.annotation.protobuf.SegmentValue.getDefaultInstance());
    }
    /**
     * <pre>
     * values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.SegmentValue value = 2;</code>
     */
    public java.util.List<datawave.annotation.protobuf.SegmentValue.Builder> 
         getValueBuilderList() {
      return getValueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        datawave.annotation.protobuf.SegmentValue, datawave.annotation.protobuf.SegmentValue.Builder, datawave.annotation.protobuf.SegmentValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            datawave.annotation.protobuf.SegmentValue, datawave.annotation.protobuf.SegmentValue.Builder, datawave.annotation.protobuf.SegmentValueOrBuilder>(
                value_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.SegmentData)
  }

  // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.SegmentData)
  private static final datawave.annotation.protobuf.SegmentData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datawave.annotation.protobuf.SegmentData();
  }

  public static datawave.annotation.protobuf.SegmentData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SegmentData>
      PARSER = new com.google.protobuf.AbstractParser<SegmentData>() {
    public SegmentData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SegmentData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SegmentData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentData> getParserForType() {
    return PARSER;
  }

  public datawave.annotation.protobuf.SegmentData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

