// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/Segment.proto

package datawave.annotation.protobuf;

/**
 * <pre>
 * scored values related to this segment
 * </pre>
 *
 * Protobuf type {@code datawave.annotation.protobuf.SegmentValue}
 */
public  final class SegmentValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.SegmentValue)
    SegmentValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SegmentValue.newBuilder() to construct.
  private SegmentValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SegmentValue() {
    value_ = "";
    score_ = 0F;
    extension_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SegmentValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            value_ = bs;
            break;
          }
          case 21: {
            bitField0_ |= 0x00000002;
            score_ = input.readFloat();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            extension_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentValue_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datawave.annotation.protobuf.SegmentValue.class, datawave.annotation.protobuf.SegmentValue.Builder.class);
  }

  private int bitField0_;
  public static final int VALUE_FIELD_NUMBER = 1;
  private volatile java.lang.Object value_;
  /**
   * <pre>
   * the value associated with this segment.
   * </pre>
   *
   * <code>required string value = 1;</code>
   */
  public boolean hasValue() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * the value associated with this segment.
   * </pre>
   *
   * <code>required string value = 1;</code>
   */
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * the value associated with this segment.
   * </pre>
   *
   * <code>required string value = 1;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORE_FIELD_NUMBER = 2;
  private float score_;
  /**
   * <pre>
   * the score associated with this value (e.g., confidence)
   * </pre>
   *
   * <code>required float score = 2;</code>
   */
  public boolean hasScore() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * the score associated with this value (e.g., confidence)
   * </pre>
   *
   * <code>required float score = 2;</code>
   */
  public float getScore() {
    return score_;
  }

  public static final int EXTENSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object extension_;
  /**
   * <pre>
   * an optional extension providing additional data.
   * </pre>
   *
   * <code>optional string extension = 3;</code>
   */
  public boolean hasExtension() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * an optional extension providing additional data.
   * </pre>
   *
   * <code>optional string extension = 3;</code>
   */
  public java.lang.String getExtension() {
    java.lang.Object ref = extension_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        extension_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * an optional extension providing additional data.
   * </pre>
   *
   * <code>optional string extension = 3;</code>
   */
  public com.google.protobuf.ByteString
      getExtensionBytes() {
    java.lang.Object ref = extension_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extension_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasValue()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasScore()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeFloat(2, score_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, extension_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, score_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, extension_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datawave.annotation.protobuf.SegmentValue)) {
      return super.equals(obj);
    }
    datawave.annotation.protobuf.SegmentValue other = (datawave.annotation.protobuf.SegmentValue) obj;

    boolean result = true;
    result = result && (hasValue() == other.hasValue());
    if (hasValue()) {
      result = result && getValue()
          .equals(other.getValue());
    }
    result = result && (hasScore() == other.hasScore());
    if (hasScore()) {
      result = result && (
          java.lang.Float.floatToIntBits(getScore())
          == java.lang.Float.floatToIntBits(
              other.getScore()));
    }
    result = result && (hasExtension() == other.hasExtension());
    if (hasExtension()) {
      result = result && getExtension()
          .equals(other.getExtension());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    if (hasScore()) {
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
    }
    if (hasExtension()) {
      hash = (37 * hash) + EXTENSION_FIELD_NUMBER;
      hash = (53 * hash) + getExtension().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datawave.annotation.protobuf.SegmentValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datawave.annotation.protobuf.SegmentValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * scored values related to this segment
   * </pre>
   *
   * Protobuf type {@code datawave.annotation.protobuf.SegmentValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.SegmentValue)
      datawave.annotation.protobuf.SegmentValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datawave.annotation.protobuf.SegmentValue.class, datawave.annotation.protobuf.SegmentValue.Builder.class);
    }

    // Construct using datawave.annotation.protobuf.SegmentValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      value_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      score_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000002);
      extension_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datawave.annotation.protobuf.Segment.internal_static_datawave_annotation_protobuf_SegmentValue_descriptor;
    }

    public datawave.annotation.protobuf.SegmentValue getDefaultInstanceForType() {
      return datawave.annotation.protobuf.SegmentValue.getDefaultInstance();
    }

    public datawave.annotation.protobuf.SegmentValue build() {
      datawave.annotation.protobuf.SegmentValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public datawave.annotation.protobuf.SegmentValue buildPartial() {
      datawave.annotation.protobuf.SegmentValue result = new datawave.annotation.protobuf.SegmentValue(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.value_ = value_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.score_ = score_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.extension_ = extension_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datawave.annotation.protobuf.SegmentValue) {
        return mergeFrom((datawave.annotation.protobuf.SegmentValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datawave.annotation.protobuf.SegmentValue other) {
      if (other == datawave.annotation.protobuf.SegmentValue.getDefaultInstance()) return this;
      if (other.hasValue()) {
        bitField0_ |= 0x00000001;
        value_ = other.value_;
        onChanged();
      }
      if (other.hasScore()) {
        setScore(other.getScore());
      }
      if (other.hasExtension()) {
        bitField0_ |= 0x00000004;
        extension_ = other.extension_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasValue()) {
        return false;
      }
      if (!hasScore()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      datawave.annotation.protobuf.SegmentValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (datawave.annotation.protobuf.SegmentValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object value_ = "";
    /**
     * <pre>
     * the value associated with this segment.
     * </pre>
     *
     * <code>required string value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * the value associated with this segment.
     * </pre>
     *
     * <code>required string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the value associated with this segment.
     * </pre>
     *
     * <code>required string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the value associated with this segment.
     * </pre>
     *
     * <code>required string value = 1;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the value associated with this segment.
     * </pre>
     *
     * <code>required string value = 1;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the value associated with this segment.
     * </pre>
     *
     * <code>required string value = 1;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      value_ = value;
      onChanged();
      return this;
    }

    private float score_ ;
    /**
     * <pre>
     * the score associated with this value (e.g., confidence)
     * </pre>
     *
     * <code>required float score = 2;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * the score associated with this value (e.g., confidence)
     * </pre>
     *
     * <code>required float score = 2;</code>
     */
    public float getScore() {
      return score_;
    }
    /**
     * <pre>
     * the score associated with this value (e.g., confidence)
     * </pre>
     *
     * <code>required float score = 2;</code>
     */
    public Builder setScore(float value) {
      bitField0_ |= 0x00000002;
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the score associated with this value (e.g., confidence)
     * </pre>
     *
     * <code>required float score = 2;</code>
     */
    public Builder clearScore() {
      bitField0_ = (bitField0_ & ~0x00000002);
      score_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object extension_ = "";
    /**
     * <pre>
     * an optional extension providing additional data.
     * </pre>
     *
     * <code>optional string extension = 3;</code>
     */
    public boolean hasExtension() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * an optional extension providing additional data.
     * </pre>
     *
     * <code>optional string extension = 3;</code>
     */
    public java.lang.String getExtension() {
      java.lang.Object ref = extension_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extension_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * an optional extension providing additional data.
     * </pre>
     *
     * <code>optional string extension = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExtensionBytes() {
      java.lang.Object ref = extension_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * an optional extension providing additional data.
     * </pre>
     *
     * <code>optional string extension = 3;</code>
     */
    public Builder setExtension(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      extension_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * an optional extension providing additional data.
     * </pre>
     *
     * <code>optional string extension = 3;</code>
     */
    public Builder clearExtension() {
      bitField0_ = (bitField0_ & ~0x00000004);
      extension_ = getDefaultInstance().getExtension();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * an optional extension providing additional data.
     * </pre>
     *
     * <code>optional string extension = 3;</code>
     */
    public Builder setExtensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      extension_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.SegmentValue)
  }

  // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.SegmentValue)
  private static final datawave.annotation.protobuf.SegmentValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datawave.annotation.protobuf.SegmentValue();
  }

  public static datawave.annotation.protobuf.SegmentValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SegmentValue>
      PARSER = new com.google.protobuf.AbstractParser<SegmentValue>() {
    public SegmentValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SegmentValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SegmentValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentValue> getParserForType() {
    return PARSER;
  }

  public datawave.annotation.protobuf.SegmentValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

