// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

public interface AnnotationMessageOrBuilder extends
                // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.v1.AnnotationMessage)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .datawave.annotation.protobuf.v1.Annotation annotations = 1;</code>
     */
    java.util.List<datawave.annotation.protobuf.v1.Annotation> getAnnotationsList();

    /**
     * <code>repeated .datawave.annotation.protobuf.v1.Annotation annotations = 1;</code>
     */
    datawave.annotation.protobuf.v1.Annotation getAnnotations(int index);

    /**
     * <code>repeated .datawave.annotation.protobuf.v1.Annotation annotations = 1;</code>
     */
    int getAnnotationsCount();

    /**
     * <code>repeated .datawave.annotation.protobuf.v1.Annotation annotations = 1;</code>
     */
    java.util.List<? extends datawave.annotation.protobuf.v1.AnnotationOrBuilder> getAnnotationsOrBuilderList();

    /**
     * <code>repeated .datawave.annotation.protobuf.v1.Annotation annotations = 1;</code>
     */
    datawave.annotation.protobuf.v1.AnnotationOrBuilder getAnnotationsOrBuilder(int index);

    /**
     * <code>string source = 2;</code>
     *
     * @return The source.
     */
    java.lang.String getSource();

    /**
     * <code>string source = 2;</code>
     *
     * @return The bytes for source.
     */
    com.google.protobuf.ByteString getSourceBytes();
}
